### PR TITLE
Feature/add visits

### PR DESCRIPTION
**Pull request by slava89**

### CODE REVIEW

**Comment by slava89** [comment]
isn't it looks hardcoded?

**Comment by andrewdacenko** [comment]
@slava89 first of all - you don't need to resolve all that data in profile. 

Also try to merge implementation into single abstraction, which depends on arguments

**Comment by andrewdacenko** [comment]
@slava89 I see a lot of code duplication

**Comment by slava89** [comment]
now need to remove old hardcoded stuff, fix lint errors. And start to make graphs

**Comment by slava89** [comment]
image

error when trying to group if "unique"

response from server comes back empty [] for total and unique

**Pull request merged**
