### PR TITLE
wip: add events

### PR DESCRIPTION
**Pull request by slava89**

### CODE REVIEW

**Comment by andrewdacenko** [comment]
@slava89 please split `routes.js` file into smaller files functionality, provided by express [`Router`](http://expressjs.com/en/4x/api.html#router).

**Comment by slava89** [comment]
resolved allUsers on new-event state to test multiselect, it's not showing the dropdown list still.. Not working yet

**Comment by slava89** [comment]
event info not showing on view for some reason, need fix

**Comment by slava89** [comment]
since find method returns array of objects added   

```
 Event.findOne({ _id: req.params.id})
        .then((data) => {
            return res.json(data);
        })
```

**Comment by slava89** [comment]
edited previous comment

**Comment by slava89** [comment]
atm we have: create new, upcoming, dismissed, search, archive. what else do we need? what was "invites" about? (which we talked about earlier)

**Comment by andrewdacenko** [comment]
@slava89 upcoming should be that events which user accepted. Invites are events that user haven't decided about.

**Comment by slava89** [comment]
bug: in upcoming events clicking on not sure not hiding event (and not removing if refresh the page)

**Pull request merged**
